# Generated by Django 5.2.5 on 2025-08-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_alter_user_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="cart",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, null=True, verbose_name="адрес"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, null=True, verbose_name="номер телефона"
            ),
        ),
    ]
