# Generated by Django 5.2.5 on 2025-08-19 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0019_remove_cart_user_remove_goodincart_cart_cart_goods"),
        ("users", "0005_user_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cart",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="mainapp.cart",
            ),
        ),
    ]
