# Generated by Django 5.2.5 on 2025-09-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="cart",
        ),
    ]
