# Generated by Django 5.2.5 on 2025-09-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0024_remove_cart_owner_alter_goodincart_cart"),
        ("users", "0008_remove_user_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cart",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="mainapp.cart",
            ),
        ),
    ]
