# Generated by Django 5.2.5 on 2025-08-08 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="sub_category",
            field=models.ManyToManyField(
                related_name="subcategories",
                to="mainapp.subcategory",
                verbose_name="Подкатегории",
            ),
        ),
        migrations.AlterField(
            model_name="good",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="mainapp.subcategory",
                verbose_name="Подкатегория товара",
            ),
        ),
    ]
