# Generated by Django 5.2.5 on 2025-08-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_category_sub_category_alter_good_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goods",
                    models.ManyToManyField(to="mainapp.good", verbose_name="Корзина"),
                ),
            ],
        ),
    ]
