# Generated by Django 5.2.5 on 2025-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_cart_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="available_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Доступное количество"
            ),
        ),
        migrations.AddField(
            model_name="good",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Признак активности"),
        ),
    ]
