# Generated by Django 5.2.5 on 2025-08-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_good_available_quantity_good_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodInCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "good",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.good",
                        verbose_name="Ссылка на товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в корзине",
                "verbose_name_plural": "Товары в корзине",
            },
        ),
        migrations.AlterField(
            model_name="cart",
            name="goods",
            field=models.ManyToManyField(
                to="mainapp.goodincart", verbose_name="Корзина"
            ),
        ),
    ]
