# Generated by Django 5.2.5 on 2025-08-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_goodincart_alter_cart_goods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="help_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Подробности подкатегории"
            ),
        ),
    ]
