# Generated by Django 5.2.5 on 2025-08-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_alter_subcategory_help_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="sub_category",
            new_name="sub_categories",
        ),
    ]
