# Generated by Django 5.2.5 on 2025-08-11 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_rename_sub_category_category_sub_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="sub_categories",
        ),
        migrations.AddField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="mainapp.category",
                verbose_name="Категория прикрепления",
            ),
        ),
    ]
