# Generated by Django 5.2.5 on 2025-08-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_remove_category_sub_categories_subcategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="help_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Подробности категории"
            ),
        ),
    ]
