# Generated by Django 5.2.5 on 2025-08-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0011_alter_subcategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="good",
            name="min_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена со скидкой",
            ),
        ),
    ]
