# Generated by Django 5.2.5 on 2025-08-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_alter_good_description_alter_good_min_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/goods/images",
                verbose_name="Картинка товара",
            ),
        ),
    ]
