# Generated by Django 5.2.5 on 2025-08-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_good_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="goods/images",
                verbose_name="Картинка товара",
            ),
        ),
    ]
