# Generated by Django 5.2.5 on 2025-08-18 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0015_remove_cart_goods_cart_user_goodincart_cart"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
