# Generated by Django 5.2.5 on 2025-08-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0018_alter_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.RemoveField(
            model_name="goodincart",
            name="cart",
        ),
        migrations.AddField(
            model_name="cart",
            name="goods",
            field=models.ManyToManyField(
                blank=True, null=True, to="mainapp.goodincart"
            ),
        ),
    ]
