# Generated by Django 5.2.5 on 2025-08-19 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0019_remove_cart_user_remove_goodincart_cart_cart_goods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="goods",
        ),
        migrations.AddField(
            model_name="goodincart",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="mainapp.cart",
            ),
        ),
    ]
