# Generated by Django 5.2.5 on 2025-08-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0020_remove_cart_goods_goodincart_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="цена доставки"
                    ),
                ),
            ],
            options={
                "verbose_name": "район доставки",
                "verbose_name_plural": "районы доставки",
            },
        ),
    ]
