# Generated by Django 5.2.5 on 2025-09-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0021_deliveryregion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodincart",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="mainapp.cart",
            ),
        ),
    ]
