# Generated by Django 5.2.5 on 2025-09-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0023_cart_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="owner",
        ),
        migrations.AlterField(
            model_name="goodincart",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="mainapp.cart",
            ),
        ),
    ]
